var pokenames = ["BULBASAUR","IVYSAUR","VENUSAUR","CHARMANDER","CHARMELEON","CHARIZARD","SQUIRTLE","WARTORTLE","BLASTOISE","CATERPIE","METAPOD","BUTTERFREE","WEEDLE","KAKUNA","BEEDRILL","PIDGEY","PIDGEOTTO","PIDGEOT","RATTATA","RATICATE","SPEAROW","FEAROW","EKANS","ARBOK","PIKACHU","RAICHU","SANDSHREW","SANDSLASH","NIDORAN?","NIDORINA","NIDOQUEEN","NIDORAN?","NIDORINO","NIDOKING","CLEFAIRY","CLEFABLE","VULPIX","NINETALES","JIGGLYPUFF","WIGGLYTUFF","ZUBAT","GOLBAT","ODDISH","GLOOM","VILEPLUME","PARAS","PARASECT","VENONAT","VENOMOTH","DIGLETT","DUGTRIO","MEOWTH","PERSIAN","PSYDUCK","GOLDUCK","MANKEY","PRIMEAPE","GROWLITHE","ARCANINE","POLIWAG","POLIWHIRL","POLIWRATH","ABRA","KADABRA","ALAKAZAM","MACHOP","MACHOKE","MACHAMP","BELLSPROUT","WEEPINBELL","VICTREEBEL","TENTACOOL","TENTACRUEL","GEODUDE","GRAVELER","GOLEM","PONYTA","RAPIDASH","SLOWPOKE","SLOWBRO","MAGNEMITE","MAGNETON","FARFETCH’D","DODUO","DODRIO","SEEL","DEWGONG","GRIMER","MUK","SHELLDER","CLOYSTER","GASTLY","HAUNTER","GENGAR","ONIX","DROWZEE","HYPNO","KRABBY","KINGLER","VOLTORB","ELECTRODE","EXEGGCUTE","EXEGGUTOR","CUBONE","MAROWAK","HITMONLEE","HITMONCHAN","LICKITUNG","KOFFING","WEEZING","RHYHORN","RHYDON","CHANSEY","TANGELA","KANGASKHAN","HORSEA","SEADRA","GOLDEEN","SEAKING","STARYU","STARMIE","MR. MIME","SCYTHER","JYNX","ELECTABUZZ","MAGMAR","PINSIR","TAUROS","MAGIKARP","GYARADOS","LAPRAS","DITTO","EEVEE","VAPOREON","JOLTEON","FLAREON","PORYGON","OMANYTE","OMASTAR","KABUTO","KABUTOPS","AERODACTYL","SNORLAX","ARTICUNO","ZAPDOS","MOLTRES","DRATINI","DRAGONAIR","DRAGONITE","MEWTWO","MEW","CHIKORITA","BAYLEEF","MEGANIUM","CYNDAQUIL","QUILAVA","TYPHLOSION","TOTODILE","CROCONAW","FERALIGATR","SENTRET","FURRET","HOOTHOOT","NOCTOWL","LEDYBA","LEDIAN","SPINARAK","ARIADOS","CROBAT","CHINCHOU","LANTURN","PICHU","CLEFFA","IGGLYBUFF","TOGEPI","TOGETIC","NATU","XATU","MAREEP","FLAAFFY","AMPHAROS","BELLOSSOM","MARILL","AZUMARILL","SUDOWOODO","POLITOED","HOPPIP","SKIPLOOM","JUMPLUFF","AIPOM","SUNKERN","SUNFLORA","YANMA","WOOPER","QUAGSIRE","ESPEON","UMBREON","MURKROW","SLOWKING","MISDREAVUS","UNOWN","WOBBUFFET","GIRAFARIG","PINECO","FORRETRESS","DUNSPARCE","GLIGAR","STEELIX","SNUBBULL","GRANBULL","QWILFISH","SCIZOR","SHUCKLE","HERACROSS","SNEASEL","TEDDIURSA","URSARING","SLUGMA","MAGCARGO","SWINUB","PILOSWINE","CORSOLA","REMORAID","OCTILLERY","DELIBIRD","MANTINE","SKARMORY","HOUNDOUR","HOUNDOOM","KINGDRA","PHANPY","DONPHAN","PORYGON2","STANTLER","SMEARGLE","TYROGUE","HITMONTOP","SMOOCHUM","ELEKID","MAGBY","MILTANK","BLISSEY","RAIKOU","ENTEI","SUICUNE","LARVITAR","PUPITAR","TYRANITAR","LUGIA","HO-OH","CELEBI","TREECKO","GROVYLE","SCEPTILE","TORCHIC","COMBUSKEN","BLAZIKEN","MUDKIP","MARSHTOMP","SWAMPERT","POOCHYENA","MIGHTYENA","ZIGZAGOON","LINOONE","WURMPLE","SILCOON","BEAUTIFLY","CASCOON","DUSTOX","LOTAD","LOMBRE","LUDICOLO","SEEDOT","NUZLEAF","SHIFTRY","TAILLOW","SWELLOW","WINGULL","PELIPPER","RALTS","KIRLIA","GARDEVOIR","SURSKIT","MASQUERAIN","SHROOMISH","BRELOOM","SLAKOTH","VIGOROTH","SLAKING","NINCADA","NINJASK","SHEDINJA","WHISMUR","LOUDRED","EXPLOUD","MAKUHITA","HARIYAMA","AZURILL","NOSEPASS","SKITTY","DELCATTY","SABLEYE","MAWILE","ARON","LAIRON","AGGRON","MEDITITE","MEDICHAM","ELECTRIKE","MANECTRIC","PLUSLE","MINUN","VOLBEAT","ILLUMISE","ROSELIA","GULPIN","SWALOT","CARVANHA","SHARPEDO","WAILMER","WAILORD","NUMEL","CAMERUPT","TORKOAL","SPOINK","GRUMPIG","SPINDA","TRAPINCH","VIBRAVA","FLYGON","CACNEA","CACTURNE","SWABLU","ALTARIA","ZANGOOSE","SEVIPER","LUNATONE","SOLROCK","BARBOACH","WHISCASH","CORPHISH","CRAWDAUNT","BALTOY","CLAYDOL","LILEEP","CRADILY","ANORITH","ARMALDO","FEEBAS","MILOTIC","CASTFORM","KECLEON","SHUPPET","BANETTE","DUSKULL","DUSCLOPS","TROPIUS","CHIMECHO","ABSOL","WYNAUT","SNORUNT","GLALIE","SPHEAL","SEALEO","WALREIN","CLAMPERL","HUNTAIL","GOREBYSS","RELICANTH","LUVDISC","BAGON","SHELGON","SALAMENCE","BELDUM","METANG","METAGROSS","REGIROCK","REGICE","REGISTEEL","LATIAS","LATIOS","KYOGRE","GROUDON","RAYQUAZA","JIRACHI","DEOXYS","TURTWIG","GROTLE","TORTERRA","CHIMCHAR","MONFERNO","INFERNAPE","PIPLUP","PRINPLUP","EMPOLEON","STARLY","STARAVIA","STARAPTOR","BIDOOF","BIBAREL","KRICKETOT","KRICKETUNE","SHINX","LUXIO","LUXRAY","BUDEW","ROSERADE","CRANIDOS","RAMPARDOS","SHIELDON","BASTIODON","BURMY","WORMADAM","MOTHIM","COMBEE","VESPIQUEN","PACHIRISU","BUIZEL","FLOATZEL","CHERUBI","CHERRIM","SHELLOS","GASTRODON","AMBIPOM","DRIFLOON","DRIFBLIM","BUNEARY","LOPUNNY","MISMAGIUS","HONCHKROW","GLAMEOW","PURUGLY","CHINGLING","STUNKY","SKUNTANK","BRONZOR","BRONZONG","BONSLY","MIME JR.","HAPPINY","CHATOT","SPIRITOMB","GIBLE","GABITE","GARCHOMP","MUNCHLAX","RIOLU","LUCARIO","HIPPOPOTAS","HIPPOWDON","SKORUPI","DRAPION","CROAGUNK","TOXICROAK","CARNIVINE","FINNEON","LUMINEON","MANTYKE","SNOVER","ABOMASNOW","WEAVILE","MAGNEZONE","LICKILICKY","RHYPERIOR","TANGROWTH","ELECTIVIRE","MAGMORTAR","TOGEKISS","YANMEGA","LEAFEON","GLACEON","GLISCOR","MAMOSWINE","PORYGON-Z","GALLADE","PROBOPASS","DUSKNOIR","FROSLASS","ROTOM","UXIE","MESPRIT","AZELF","DIALGA","PALKIA","HEATRAN","REGIGIGAS","GIRATINA","CRESSELIA","PHIONE","MANAPHY","DARKRAI","SHAYMIN","ARCEUS","VICTINI","SNIVY","SERVINE","SERPERIOR","TEPIG","PIGNITE","EMBOAR","OSHAWOTT","DEWOTT","SAMUROTT","PATRAT","WATCHOG","LILLIPUP","HERDIER","STOUTLAND","PURRLOIN","LIEPARD","PANSAGE","SIMISAGE","PANSEAR","SIMISEAR","PANPOUR","SIMIPOUR","MUNNA","MUSHARNA","PIDOVE","TRANQUILL","UNFEZANT","BLITZLE","ZEBSTRIKA","ROGGENROLA","BOLDORE","GIGALITH","WOOBAT","SWOOBAT","DRILBUR","EXCADRILL","AUDINO","TIMBURR","GURDURR","CONKELDURR","TYMPOLE","PALPITOAD","SEISMITOAD","THROH","SAWK","SEWADDLE","SWADLOON","LEAVANNY","VENIPEDE","WHIRLIPEDE","SCOLIPEDE","COTTONEE","WHIMSICOTT","PETILIL","LILLIGANT","BASCULIN","SANDILE","KROKOROK","KROOKODILE","DARUMAKA","DARMANITAN","MARACTUS","DWEBBLE","CRUSTLE","SCRAGGY","SCRAFTY","SIGILYPH","YAMASK","COFAGRIGUS","TIRTOUGA","CARRACOSTA","ARCHEN","ARCHEOPS","TRUBBISH","GARBODOR","ZORUA","ZOROARK","MINCCINO","CINCCINO","GOTHITA","GOTHORITA","GOTHITELLE","SOLOSIS","DUOSION","REUNICLUS","DUCKLETT","SWANNA","VANILLITE","VANILLISH","VANILLUXE","DEERLING","SAWSBUCK","EMOLGA","KARRABLAST","ESCAVALIER","FOONGUS","AMOONGUSS","FRILLISH","JELLICENT","ALOMOMOLA","JOLTIK","GALVANTULA","FERROSEED","FERROTHORN","KLINK","KLANG","KLINKLANG","TYNAMO","EELEKTRIK","EELEKTROSS","ELGYEM","BEHEEYEM","LITWICK","LAMPENT","CHANDELURE","AXEW","FRAXURE","HAXORUS","CUBCHOO","BEARTIC","CRYOGONAL","SHELMET","ACCELGOR","STUNFISK","MIENFOO","MIENSHAO","DRUDDIGON","GOLETT","GOLURK","PAWNIARD","BISHARP","BOUFFALANT","RUFFLET","BRAVIARY","VULLABY","MANDIBUZZ","HEATMOR","DURANT","DEINO","ZWEILOUS","HYDREIGON","LARVESTA","VOLCARONA","COBALION","TERRAKION","VIRIZION","TORNADUS","THUNDURUS","RESHIRAM","ZEKROM","LANDORUS","KYUREM","KELDEO","MELOETTA","GENESECT","CHESPIN","QUILLADIN","CHESNAUGHT","FENNEKIN","BRAIXEN","DELPHOX","FROAKIE","FROGADIER","GRENINJA","BUNNELBY","DIGGERSBY","FLETCHLING","FLETCHINDER","TALONFLAME","SCATTERBUG","SPEWPA","VIVILLON","LITLEO","PYROAR","FLABEBE","FLOETTE","FLORGES","SKIDDO","GOGOAT","PANCHAM","PANGORO","FURFROU","ESPURR","MEOWSTIC","HONEDGE","DOUBLADE","AEGISLASH","SPRITZEE","AROMATISSE","SWIRLIX","SLURPUFF","INKAY","MALAMAR","BINACLE","BARBARACLE","SKRELP","DRAGALGE","CLAUNCHER","CLAWITZER","HELIOPTILE","HELIOLISK","TYRUNT","TYRANTRUM","AMAURA","AURORUS","SYLVEON","HAWLUCHA","DEDENNE","CARBINK","GOOMY","SLIGGOO","GOODRA","KLEFKI","PHANTUMP","TREVENANT","PUMPKABOO","GOURGEIST","BERGMITE","AVALUGG","NOIBAT","NOIVERN","XERNEAS","YVELTAL","ZYGARDE","DIANCIE","HOOPA","VOLCANION","ROWLET","DARTRIX","DECIDUEYE","LITTEN","TORRACAT","INCINEROAR","POPPLIO","BRIONNE","PRIMARINA","PIKIPEK","TRUMBEAK","TOUCANNON","YUNGOOS","GUMSHOOS","GRUBBIN","CHARJABUG","VIKAVOLT","CRABRAWLER","CRABOMINABLE","ORICORIO","CUTIEFLY","RIBOMBEE","ROCKRUFF","LYCANROC","WISHIWASHI","MAREANIE","TOXAPEX","MUDBRAY","MUDSDALE","DEWPIDER","ARAQUANID","FOMANTIS","LURANTIS","MORELULL","SHIINOTIC","SALANDIT","SALAZZLE","STUFFUL","BEWEAR","BOUNSWEET","STEENEE","TSAREENA","COMFEY","ORANGURU","PASSIMIAN","WIMPOD","GOLISOPOD","SANDYGAST","PALOSSAND","PYUKUMUKU","TYPE: NULL","SILVALLY","MINIOR","KOMALA","TURTONATOR","TOGEDEMARU","MIMIKYU","BRUXISH","DRAMPA","DHELMISE","JANGMO-O","HAKAMO-O","KOMMO-O","TAPU KOKO","TAPU LELE","TAPU BULU","TAPU FINI","COSMOG","COSMOEM","SOLGALEO","LUNALA","NIHILEGO","BUZZWOLE","PHEROMOSA","XURKITREE","CELESTEELA","KARTANA","GUZZLORD","NECROZMA","MAGEARNA","MARSHADOW","POIPOLE","NAGANADEL","BLACEPHALON","STAKATAKA","ZERAORA","MELTAN","MELMETAL","GROOKEY","THWACKEY","RILLABOOM","SCORBUNNY","RABOOT","CINDERACE","SOBBLE","DRIZZILE","INTELEON","SKWOVET","GREEDENT","ROOKIDEE","CORVISQUIRE","CORVIKNIGHT","BLIPBUG","DOTTLER","ORBEETLE","NICKIT","THIEVUL","GOSSIFLEUR","ELDEGOSS","WOOLOO","DUBWOOL","CHEWTLE","DREDNAW","YAMPER","BOLTUND","ROLYCOLY","CARKOL","COALOSSAL","APPLIN","FLAPPLE","APPLETUN","SILICOBRA","SANDACONDA","CRAMORANT","ARROKUDA","BARRASKEWDA","TOXEL","TOXTRICITY","SIZZLIPEDE","CENTISKORCH","CLOBBOPUS","GRAPPLOCT","SINISTEA","POLTEAGEIST","HATENNA","HATTREM","HATTERENE","IMPIDIMP","MORGREM","GRIMMSNARL","OBSTAGOON","PERRSERKER","CURSOLA","SIRFETCHD","MRRIME","RUNERIGUS","MILCERY","ALCREMIE","FALINKS","PINCURCHIN","SNOM","FROSMOTH","STONJOURNER","EISCUE","INDEEDEE","MORPEKO","CUFANT","COPPERAJAH","DRACOZOLT","ARCTOZOLT","DRACOVISH","ARCTOVISH","DURALUDON","DREEPY","DRAKLOAK","DRAGAPULT","ZACIAN","ZAMAZENTA","ETERNATUS"];

var prevSubmit = [];
var count = 0;
var countSpan = document.getElementById("counter").getElementsByTagName("span")[0];
var timerDiv = document.getElementById("timer");
var seconds = 0;
var pluralS = "second";
var pluralM = "minute";
var minutes = 0;
var firstTime = true;



function storageInit() {
/*  console.log(localStorage.getItem("prevSubmitLS") === null);
  console.log(localStorage.getItem("prevSubmitLS"));
    console.log(localStorage.getItem("countLS"));
    console.log(localStorage.getItem("secondsLS"));
  if(localStorage.getItem("prevSubmitLS") === null){
    console.log('retrieving local storage');
    prevSubmit = localStorage.getItem('prevSubmitLS');
    console.log('prevSubmit = ' + prevSubmit);
    count = localStorage.getItem('countLS');
    minutes = localStorage.getItem('minutesLS');
    seconds = localStorage.getItem('secondsLS');
 }
else {
  storageUpdate(); 
 }
*/}
function storageUpdate() {
  /*console.log('updating storage');
  localStorage.setItem('prevSubmitLS', prevSubmit);
  localStorage.setItem('countLS', count);
  localStorage.setItem('secondsLS', seconds);
  localStorage.setItem('minutesLS', minutes);  
  //must use get in order for data to persist, for some reason
  localStorage.getItem('prevSubmitLS');
 localStorage.getItem('countLS');
localStorage.getItem('minutesLS');
localStorage.getItem('secondsLS');
*/}

function timer() {
seconds += 1;
if(seconds>=60) {
seconds = seconds%60;
minutes +=1;
}
if(seconds==1){
pluralS = "second";
}else {pluralS = "seconds";}
if(minutes==1) {
pluralM = "minute";
}else {pluralM = "minutes";}
if(minutes>0) {
timerDiv.innerHTML = minutes + " " + pluralM + " " + seconds + " " + pluralS;
}
else {timerDiv.innerHTML = seconds + " " + pluralS;}
}
function check() {
if(firstTime) {
setInterval(timer, 1000);

}
firstTime = false;
var input = document.getElementsByTagName("input")[0].value.toUpperCase().replace(/[^a-zA-Z0-9]/g, "");
//console.log(input);

var skip = false;
for (var i=0;i<prevSubmit.length;i++){
if(input==prevSubmit[i]){
skip=true;
}
}

var correct=false;
for(var i=0; !skip && !correct && i<pokenames.length; i++) {
if(input==pokenames[i].replace(/[^a-zA-Z0-9]/g, "")) {
correct=true;
count++;
prevSubmit.push(input);
var li = document.createElement('li');

switch(input) {
case "MRMIME": input = "Mr. Mime";
break;
case "MIMEJR": input = "Mime Jr.";
break;
case "TYPENULL": input = "Type: Null";
break;
case "TAPULELE": input = "Tapu Lele";
break;
case "TAPUBULU": input = "Tapu Bulu";
break;
case "TAPUKOKO": input = "Tapu Koko";
break;
case "TAPUFINI": input = "Tapu Fini";
break;
case "JANGMOO": input = "Jangmo-o";
break;
case "HAKAMOO": input = "Hakamo-o";
break;
case "KOMMOO": input = "Kommo-o";
break;
case "PORYGONZ": input = "Porygon-Z";
break;
case "HOOH": input = "Ho-Oh";
break;
case "FLABEBE": input = "Flab&eacute;b&eacute;";
break;
case "FARFETCHD": input = "Farfetch'd";
break;
case "SIRFETCHD": input = "Sirfetch'd";
break;
case "MRRIME": input = "Mr. Rime";
break;
default: input = input[0] + input.substring(1).toLowerCase();
}
li.innerHTML = input;
document.getElementById("list").appendChild(li);
}
}
countSpan.innerHTML = count;
  storageUpdate();
document.getElementsByTagName("input")[0].value = "";
}
